### PR TITLE
New theme for Mission Control

### PR DESCRIPTION
**Pull request by GermanDZ**
Just updating the login theme from the upstream (https://github.com/StuartApp/keycloak) to reflect the latest changes from https://github.com/StuartApp/keycloak/pull/6

### CODE REVIEW

**Review by BuonOmo — APPROVED** [review]
@GermanDZ I'm not seeing the theme with a simple `make down; make`. I've noticed that this is due to me using the 12.0.X version of keycloak, and bypassing the first import!

And importing the 11 settings in the 12 did not work, obviously...

Anyway, I'll trust you on that one and will see the result later! Tell me if you want help on traducing settings fro 11 to 12

**Comment by GermanDZ** [comment]
> 

To re-build the image you can do `make build-image && make start`. Building the image will include the latest _theme_, but keep the same DB, then make start will run the same old keycloak install with the new image. As long you keep the `KEYCLOAK_VERSION` unchanged you should not see any problem.

**Comment by BuonOmo** [comment]
@GermanDZ the previous theme was not working either since I've never imported the config from `exported_configs` for keycloak 12. Does that make sense?

**Comment by GermanDZ** [comment]
> @GermanDZ the previous theme was not working either since I've never imported the config from `exported_configs` for keycloak 12. Does that make sense?
> 
> BTW, by not working, I mean that it is not even visible as an option in the client's panel in the admin

Yeap, could be possible, some exported configs weren't good replicas from production.

**Pull request merged**
