### PR TITLE
Add version for keycloak-config-cli in init steps

### PR DESCRIPTION
**Pull request by GermanDZ**
Just some missing env vars.

### CODE REVIEW

**Review by BuonOmo — COMMENTED** [review]
This will break as soon as we try to use another version for this script :/

I'm in the process of refactoring, can I try and find something smarter to make it work?

**Comment by GermanDZ** [comment]
> This will break as soon as we try to use another version for this script :/
> 
> I'm in the process of refactoring, can I try and find something smarter to make it work?

Yes, please iterate on it.

I'm usually going for the cycle: "make it work, make it right, make it xxxx" (xxxx = fast/configurable/standard depending on the case)

Since we are not going to release the "keycloak for local and all envs", these tasks are pretty irrelevant now. But they helped me to know better how Keycloak behaves in different scenarios.

**Comment by GermanDZ** [comment]
I went for a dedicated env var for config-cli, It's not easy to know which version we need for each case.

**Comment by BuonOmo** [comment]
@GermanDZ ok we can merge that one now and in the refacto i'll show you my proposition (which is basically: use `KEYCLOAK_VERSION` unless KEYCLOAK_VERSION=11.0.x, then use 11.0.3

**Pull request merged**
